"""How different are the two price feeds, really?

We download the same symbols twice, from two sources, and the reason is not
thoroughness for its own sake.

**SIP** is the consolidated tape: every US exchange merged into one stream. It
is complete, it has full history, and it is what the backtest is measured on.
It is also delayed by fifteen minutes on the free tier, which makes it useless
for trading.

**IEX** is a single exchange. It is free and real-time, and it is therefore the
only thing the live system can actually see. It is also small.

So the rehearsal and the real performance run on different information, and
every conclusion drawn from the backtest has to survive the translation. This
script measures the size of that translation before anything is built on top of
it, because the honest time to find out that a rule cannot run is now, not in
September.

It reports three things per symbol:

- **Coverage.** What fraction of SIP's minutes exist on IEX at all. A minute in
  which nothing trades on IEX produces no bar, and a missing bar is not a quiet
  minute -- it is a hole. Our `mean_volume` deliberately refuses to average
  over a window that reaches across a hole, so every hole silences the strategy
  for the length of that window.
- **Volume share.** What fraction of the traded volume IEX sees. This is the
  number that decides whether a rule about volume means the same thing in both
  places.
- **The worst days.** Because an average hides an outage, and an outage is the
  case that matters.

Usage:
    python scripts/compare_feeds.py                     # print
    python scripts/compare_feeds.py --write             # also write results/
"""

from __future__ import annotations

import argparse
import collections
import csv
import io
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
DATA = os.path.join(ROOT, "data")
RESULTS = os.path.join(ROOT, "results")

SYMBOLS = ["SPY", "QQQ", "IWM", "AAPL", "MSFT", "NVDA", "AMD", "TSLA", "META", "AMZN"]
START = "2021-07-01"
END = "2026-08-27"

# A session losing this many minutes is counted as damaged. Twenty is not
# arbitrary: it is the strategy's volume-comparison window, so a hole this
# size or larger is guaranteed to silence the rule rather than merely thin it.
DAMAGED_SESSION_MINUTES = 20


def read(symbol, feed):
    """Timestamps, total volume, and bars per session for one file."""
    path = os.path.join(DATA, "%s_1min_%s_%s_%s.csv" % (symbol, feed, START, END))
    if not os.path.exists(path):
        raise SystemExit("missing %s -- run scripts/download_all_bars.py first" % path)
    stamps = set()
    volume = 0.0
    per_session = collections.Counter()
    with io.open(path, encoding="utf-8", newline="") as handle:
        for row in csv.DictReader(handle):
            stamps.add(row["t_utc"])
            volume += float(row["volume"])
            per_session[row["session"]] += 1
    return stamps, volume, per_session


def compare(symbol):
    sip_stamps, sip_volume, sip_sessions = read(symbol, "sip")
    iex_stamps, iex_volume, iex_sessions = read(symbol, "iex")

    # If IEX carried a minute SIP does not, one of them is wrong about what a
    # trading minute is, and every comparison below would be meaningless.
    orphans = len(iex_stamps - sip_stamps)

    dead = sorted(d for d in sip_sessions if iex_sessions.get(d, 0) == 0)
    damaged = sorted(
        (sip_sessions[d] - iex_sessions.get(d, 0), d)
        for d in sip_sessions
        if sip_sessions[d] - iex_sessions.get(d, 0) >= DAMAGED_SESSION_MINUTES
    )
    return {
        "symbol": symbol,
        "sip_bars": len(sip_stamps),
        "iex_bars": len(iex_stamps),
        "coverage": 100.0 * len(iex_stamps) / len(sip_stamps),
        "volume_share": 100.0 * iex_volume / sip_volume,
        "orphans": orphans,
        "sessions": len(sip_sessions),
        "dead_sessions": dead,
        "damaged_sessions": len(damaged),
        "worst": sorted(damaged, reverse=True)[:3],
    }


def render(rows):
    out = []
    w = out.append
    w("# How much of the market the live system can actually see")
    w("")
    w("Generated by `scripts/compare_feeds.py` from %s to %s, both ends inclusive."
      % (START, END))
    w("")
    w("The backtest is measured on the **SIP** feed -- the consolidated tape,")
    w("every US exchange merged. The live system can only use **IEX**, a single")
    w("exchange, because that is what the free tier gives us in real time. This")
    w("table is the size of the gap between the two.")
    w("")
    w("| Symbol | SIP minutes | IEX minutes | IEX has | IEX sees | Damaged sessions |")
    w("| --- | ---: | ---: | ---: | ---: | ---: |")
    for r in rows:
        w("| %s | %s | %s | %.1f%% | %.2f%% of volume | %d of %d |" % (
            r["symbol"], "{:,}".format(r["sip_bars"]), "{:,}".format(r["iex_bars"]),
            r["coverage"], r["volume_share"], r["damaged_sessions"], r["sessions"]))
    w("")
    w("**IEX minutes** counts the minutes that exist on IEX at all. A minute in")
    w("which nothing traded on IEX produces no bar -- and a missing bar is a")
    w("hole, not a quiet minute.")
    w("")
    w("**A damaged session** is one where IEX is missing %d or more minutes."
      % DAMAGED_SESSION_MINUTES)
    w("That number is the strategy's volume-comparison window, so a hole this")
    w("size is guaranteed to silence the rule rather than merely thin it.")
    w("")

    dead = sorted({d for r in rows for d in r["dead_sessions"]})
    if dead:
        w("## Days IEX saw nothing at all")
        w("")
        for day in dead:
            hit = [r["symbol"] for r in rows if day in r["dead_sessions"]]
            w("- **%s** -- no IEX bars on %d of %d symbols (%s)."
              % (day, len(hit), len(rows), ", ".join(hit)))
        w("")
        w("A full session with no data is not a thin day, it is an outage. The")
        w("live system would have seen nothing, formed no view, and traded")
        w("nothing. That is the correct behaviour and it must be the *designed*")
        w("behaviour: a trader that treats an absent feed as a calm market is a")
        w("trader that acts on a stale price.")
        w("")

    w("## What this means for the strategy")
    w("")
    w("1. **The volume rule does not mean the same thing on both feeds.** IEX")
    w("   sees roughly one fiftieth of the trading. \"This minute was 1.2 times")
    w("   busier than usual\" is measured against a base that small, so it is a")
    w("   far noisier judgement live than in the rehearsal. The threshold has")
    w("   to be swept separately on each feed, and a value that only works on")
    w("   SIP is a value we cannot use.")
    w("")
    w("2. **The day's average price is an estimate on IEX, not a measurement.**")
    w("   It is computed from a few per cent of the volume. The distance from")
    w("   it -- the entire entry signal -- inherits that error.")
    w("")
    w("3. **Expect fewer trades live than in the backtest, before any other")
    w("   effect.** Holes silence the rule for a full window each. The")
    w("   150-trade power floor has to be checked against the IEX count, which")
    w("   is the number of trades we would really get, not the SIP count.")
    return "\n".join(out) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true",
                        help="write results/feed_coverage.md as well as printing")
    args = parser.parse_args()

    rows = []
    for symbol in SYMBOLS:
        row = compare(symbol)
        if row["orphans"]:
            print("WARNING: %s has %d IEX bars with no SIP counterpart"
                  % (symbol, row["orphans"]), file=sys.stderr)
        rows.append(row)
        print("%-6s SIP %s  IEX %s  %5.1f%% of minutes  %5.2f%% of volume  "
              "%3d damaged sessions"
              % (row["symbol"], "{:,}".format(row["sip_bars"]),
                 "{:,}".format(row["iex_bars"]), row["coverage"],
                 row["volume_share"], row["damaged_sessions"]))

    report = render(rows)
    if args.write:
        os.makedirs(RESULTS, exist_ok=True)
        path = os.path.join(RESULTS, "feed_coverage.md")
        with io.open(path, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(report)
        print("\nwrote %s" % path)
    return 0


if __name__ == "__main__":
    sys.exit(main())
